language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
env:
    - REQUESTS=requests==1.2.2
    - REQUESTS=requests
install: pip install mock pytest pytest-cov coveralls $REQUESTS --use-mirrors --upgrade
script: py.test --cov
after_success:
    - coveralls
notifications:
    email:
        - jturk@sunlightfoundation.com
matrix:
    exclude:
        - python: "3.4"
          env: REQUESTS=requests==1.2.2
